data:
  APPINSIGHTS_INSTRUMENTATIONKEY: ODM3Yjc5N2YtMDQwMi00MjIyLTk3ZGItMDJmNzQ5YjBmYzE4
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjQ=
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dHJ1Y252c3RvcmFnZTtBY2NvdW50S2V5PVZmYmptZjZvN1VQTUhuVXZZUVVMeFNORW5SSWpIZ0QwRzBHb0FmY1RDb2diWTF2NEZjVnRyV0Q1MzdZclN2TTU2SmNOUjBEOUZJeUUrQVN0c0FwcHVBPT0=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dHJ1Y252c3RvcmFnZTtBY2NvdW50S2V5PVJZY2NZaTVrOHJMOCtrZDdER01JdFM2UzRDRXRjMTZIZ2VCVzdzZ1pTMGJVLytkWHl6WEpiQ2ZZTVJsVGNoaHNtRTJHazF3T0JYdFcrQVN0NklGMHNnPT0=
  WEBSITE_CONTENTSHARE: dHJ1Y252ZnVuY3Rpb25hcHBlNzRkYjhmZmNhNDI=
  MyDbConnection: bW9uZ29kYjovL3RydWNudmNvc21vc2RiOmFMVHJJSGEwQ0NPWmhoSnhKNTZkV0VHQTFMNnQzdElGa0ppWmU3Vm10bVNqaGsxR01KeHVaTDZMZnhqYVp6eEFRQXd1RXBGVDNxZnpBQ0RiZUtSejdBPT1AdHJ1Y252Y29zbW9zZGIubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUB0cnVjbnZjb3Ntb3NkYkA=
apiVersion: v1
kind: Secret
metadata:
  name: trucnvaks
---
data:
  host.master: UnZ0NnZMX2dYUHhCcVhxd3hXZ1N4YTlubXlJS3h6a3h1SkdYWkZGM0h5SjdBekZ1V3dOOGJRPT0=
  host.function.default: TktHc0pDeFRxbTN3YUg1OFdZSFdxOEZoX0lJOEk1Qm1OWDdtSHp4dWVhQkZBekZ1YllXS1BnPT0=
  host.systemKey.default: d2I5cjU5aEw1d29ydE5RV0M0U1BHc2FGcDhsWldhTWRaNVpMY2hlTU5DUmxBekZ1dkM0RTdnPT0=
  functions.createadvertisement.default: blUzZzJ2NDJMZGdhN3M4MWo1eWI3VHh1Rk1DOU5TSDJDTXRjZ1UwVzNyREpBekZ1U1R5NkVRPT0=
  functions.deleteadvertisement.default: Rll4S3FXQ3RsZ2FLZlRCc2RvdFJtNWpzN1EwVEhHeXpyTVlUbmFQcmFPc3dBekZ1VjJKWFFnPT0=
  functions.getadvertisement.default: cFhLV1N0ZTQ1R1pZQkhmYUxnVFlkcm1jNjA2YlVTaW5rVjk4bHVyYlRid0JBekZ1SzlGXzV3PT0=
  functions.getadvertisements.default: VjVzNV9EMjRXa19lZExDR01JQmtjME1SWXh2akFvVWt0RkdqU2pObGVLQXVBekZ1clBoOXp3PT0=
  functions.getpost.default: RUZ0SUJZRDBjV3A5a09fZzNlM1NWZHVqaWQ4ZTNCWVZJekJpZDh0bXV4YVlBekZ1RmlzU0t3PT0=
  functions.getposts.default: dm1MaDdxOE13WXY4S2RlOGNTNXhpdkE5Z2pmV09kaDZBQ3FqWWJoQVF1Z0dBekZ1Z2tUTTdnPT0=
  functions.updateadvertisement.default: akhmQkhSZTVDR3JwWmVtcHA5NlZFemFLcjdZSVpsM2RaSnhyQlF1ejRXVmxBekZ1YWMwVWhBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-trucnvaks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trucnvaks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: trucnvaks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trucnvaks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: trucnvaks-http
spec:
  selector:
    app: trucnvaks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucnvaks-http
  labels:
    app: trucnvaks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trucnvaks-http
  template:
    metadata:
      labels:
        app: trucnvaks-http
    spec:
      containers:
      - name: trucnvaks-http
        image: trucnvacr.azurecr.io/trucnvaks:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-trucnvaks
        envFrom:
        - secretRef:
            name: trucnvaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: trucnvaks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucnvaks
  labels:
    app: trucnvaks
spec:
  selector:
    matchLabels:
      app: trucnvaks
  template:
    metadata:
      labels:
        app: trucnvaks
    spec:
      containers:
      - name: trucnvaks
        image: trucnvacr.azurecr.io/trucnvaks:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: trucnvaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: trucnvaks-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: trucnvaks
  labels: {}
spec:
  scaleTargetRef:
    name: trucnvaks
  triggers:
  - type: azure-eventhub
    metadata:
      direction: in
      eventHubName: trucnvevenhub
      connectionFromEnv: Endpoint=sb://trucnvnamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=aMatTsN/wm+oZfjgOeU7PnJx3HpHzl7UE+AEhHWv+7A=
---

