data:
  APPINSIGHTS_INSTRUMENTATIONKEY: MGRjNjg1MDAtOGUzNy00MzhmLTllZTctMWViNTA0MWY0ZmVh
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjQ=
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dHJ1Y252c3RvcmFnZTtBY2NvdW50S2V5PVJZY2NZaTVrOHJMOCtrZDdER01JdFM2UzRDRXRjMTZIZ2VCVzdzZ1pTMGJVLytkWHl6WEpiQ2ZZTVJsVGNoaHNtRTJHazF3T0JYdFcrQVN0NklGMHNnPT0=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9dHJ1Y252c3RvcmFnZTtBY2NvdW50S2V5PVJZY2NZaTVrOHJMOCtrZDdER01JdFM2UzRDRXRjMTZIZ2VCVzdzZ1pTMGJVLytkWHl6WEpiQ2ZZTVJsVGNoaHNtRTJHazF3T0JYdFcrQVN0NklGMHNnPT0=
  WEBSITE_CONTENTSHARE: dHJ1Y252ZnVuY3Rpb25hcHBlNzRkYjhmZmNhNDI=
  MyDbConnection: bW9uZ29kYjovL3RydWNudmNvc21vc2RiOkZiall3RUF5MmxzbjdUSFFyaHhBM3VUOWgwSE9XVEt0U0ZWUXNzYkxHVWRLR2cwRXBwczRaZnk4Qmk3ZFdGSkhWVXRBc1FBTTNFS1JBQ0RiVzJYOEhBPT1AdHJ1Y252Y29zbW9zZGIubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUB0cnVjbnZjb3Ntb3NkYkA=
apiVersion: v1
kind: Secret
metadata:
  name: trucnvaks
---
data:
  host.master: dUk4NlRqQUxIbUpFaFBEVnBvVjBTblFSc00yY19CbUg3emh5TDZ6UjFzQVhBekZ1RTN5c2RRPT0=
  host.function.default: T2tfX3NmYk9ZVUJxUmY1cUJYQUNVZHFpaTJnWDRzWHFGcHExWVRVdWUyQzNBekZ1ZHI5YVVnPT0=
  host.systemKey.default: V0VEX1JrOWVJVlhES2xidHo2b2hVcUZuWHl1ZEktVExOal9QZ01GZHJORWxBekZ1c05HRWdBPT0=
  functions.createadvertisement.default: WFRBaHI3WFVtclFPN2wycm1TUUY1QXFSLW1qVnZySnY0MExmTERQVzZNamRBekZ1Mk55YzNBPT0=
  functions.deleteadvertisement.default: Rlg4X0NHeWtyM2ozckpJWGNWZVBnQ1N2X1dEX2ZMZjFORjVyLVF5am9lbFZBekZ1TS13cktRPT0=
  functions.getadvertisement.default: NWpHZTlEaEtZdnF0RWF5Y2JFVVQ5c05YY2dMOWpVd001RWJYcVBkSHRkOWtBekZ1cFE4Wlp3PT0=
  functions.getadvertisements.default: dkw2eW1SQ0prUi15MVJrVHd0cFUxbFJfYUMtY09TcFRKSUhTb1NsSkZYN1NBekZ1NDNXbm1nPT0=
  functions.getpost.default: d2lMMU9mN20wUml1TGxiTmJyRGJiTGVLUG1TcGtKVFBsWjNtRlF2ZXcwbEJBekZ1U3lRWGVRPT0=
  functions.getposts.default: RENiQ1pKbkVQZUFpQmZGNzlINXo2T0x4VmN3OWVEcndlaTlISUlJRkNpM2VBekZ1ejRjb3BRPT0=
  functions.updateadvertisement.default: dW5GUGVlR0ZnR2I4WlNkNUZ0cHdBV1pQSmt0MFpCZ3NYRXFmOXJIOWFRVjhBekZ1ZGtoOFRRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-trucnvaks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trucnvaks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: trucnvaks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trucnvaks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: trucnvaks-http
spec:
  selector:
    app: trucnvaks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucnvaks-http
  labels:
    app: trucnvaks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trucnvaks-http
  template:
    metadata:
      labels:
        app: trucnvaks-http
    spec:
      containers:
      - name: trucnvaks-http
        image: trucnvacr.azurecr.io/trucnvaks:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-trucnvaks
        envFrom:
        - secretRef:
            name: trucnvaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: trucnvaks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucnvaks
  labels:
    app: trucnvaks
spec:
  selector:
    matchLabels:
      app: trucnvaks
  template:
    metadata:
      labels:
        app: trucnvaks
    spec:
      containers:
      - name: trucnvaks
        image: trucnvacr.azurecr.io/trucnvaks:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: trucnvaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: trucnvaks-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: trucnvaks
  labels: {}
spec:
  scaleTargetRef:
    name: trucnvaks
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

